"""shared_schema_setup

Revision ID: e6c3ff258c30
Revises: 
Create Date: 2025-02-11 15:46:47.400113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# from alembic_default.tenant import for_each_tenant

# revision identifiers, used by Alembic.
revision: str = 'e6c3ff258c30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# @for_each_tenant
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schema', sa.String(), nullable=False),
    sa.Column('default_tenant', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1000), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant')),
    schema='shared'
    )
    op.create_table('user',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1000), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['shared.tenant.id'], name=op.f('fk_user_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    schema='shared'
    )
    # ### end Alembic commands ###


# @for_each_tenant
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user', schema='shared')
    op.drop_table('tenant', schema='shared')
    # ### end Alembic commands ###
