version: 1
disable_existing_loggers: false

formatters:
    console:
        format: "[%(asctime)s][%(levelname)s][%(name)s] %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    file:
        format: "[%(asctime)s][%(levelname)s][%(name)s] %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
    network:
        format: "[sampleProject][%(levelname)s] %(message)s"

handlers:
    console:
        class: src.logging.utils.ColorHandler
        level: INFO
        formatter: console
        stream: ext://sys.stdout
        colors:
          debug: magenta
          info: cyan
          warning: yellow
          error: red
          critical: red

    file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: file
        filename: ./logs/worker/info.log
        when: 'midnight'
        backupCount: 5
        encoding: utf8

    error:
        class: logging.handlers.TimedRotatingFileHandler
        level: ERROR
        formatter: file
        filename: ./logs/worker/error.log
        when: 'midnight'
        backupCount: 5
        encoding: utf8


root:
    level: INFO
    handlers: [ console, error, file_handler ]
    propagate: no


loggers:
    celery:
        level: INFO
        handlers: [ console, error, file_handler ]
        propagate: no